version: "3.5"
services:
  spring-boot:
    image: spring-boot
    build:
      context: .
    ports:
      - "8080:8082" #HTTP
      - "5005:5005" #DEBUG
    volumes:
      - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven
      #- ${MAVEN_SETTINGS_FOLDER}:/root/.m2   # comentar la línea si no quieres usar las configuraciones locales de maven, o no tienes maven instalado
